- name: DEPLY AS£ DECLARATION
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    uri_method: POST
    

  vars_file:  
    - ../creds/creds.yaml

  tasks: 
  - name: Create a JIRA issue
    uri:
      url: https://3.9.54.62/mgmt/shared/appsvcs/declare
      user: "{{big-ip_user}}"
      password: "{{big-ip_pass}}"
      method: "{{uri_method}}"
      body: "{{ lookup('file','./as3-json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
